name: BotTemplate - Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: BotTemplate - Install dependencies
      run: |
        nuget sources add -name "github" -Source https://nuget.pkg.github.com/Viincenttt/index.json -StorePasswordInClearText -Username Viincenttt -Password ${{ secrets.PAT_TOKEN }}
        dotnet restore
      working-directory: src
      env:
        Password: ${{ secrets.PAT_TOKEN }}
    - name: TradingBot - Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: TradingBot - Run tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: src
      