name: BotTemplate - Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/owner/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.PAT_TOKEN}}
      working-directory: src
    - name: BotTemplate - Install dependencies
      run: dotnet restore
      working-directory: src
    - name: TradingBot - Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: TradingBot - Run tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: src
      