name: BotTemplate - Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101        
    - name: Ensure GitHub NuGet Source
      run: | 
        nuget sources remove -name "github"
        nuget sources add -name "github" -Source https://nuget.pkg.github.com/Viincenttt/index.json -StorePasswordInClearText -Username Viincenttt -Password ${{ secrets.PAT_TOKEN }}
        nuget restore
      working-directory: src
    - name: TradingBot - Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: TradingBot - Run tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: src
      